### ISSUE TITLE
[Game] The Secret World - "Failed to Initialize GUI/Rendering System"

### ISSUE THREAD

**Issue by PadreAdamo** [iXit/Mesa-3D#275] opened 2017-03-10 00:27 UTC
This is another game that is doing a check for a valid adapter and displays a similar and DEBUG as Wildstar. The NINE_DEBUG=all 

err:d3d9nine:present_has_d3dadapter Failed to load /usr/lib/d3d/d3dadapter9.so.1: /usr/lib/d3d/d3dadapter9.so.1: cannot open shared object file: No such file or directory
err:d3d9nine:present_has_d3dadapter 
Native Direct3D 9 will be unavailable.
For more information visit https://wiki.ixit.cz/d3d9
err:d3d9nine:d3dadapter9_new Your display driver doesn't support native D3D9 adapters.

This game is known to  have some "shadow rendering" issues. Though, I have yet to have seen anyone running it with Wine Nine. Perhaps this is a blocker.

Opensuse Tumbleweed
Radeon 7970

There are other Wine Nine games I do play and they do not give me any errors. In particular, Guild Wars 2.

**Comment by PadreAdamo** [comment] 2017-03-15 23:38
I am loading up another distro and will try on that; Ubuntu w/Padoka PPA. I will report my findings back here.

**Comment by siro20** [comment] 2017-04-06 17:01
Duplicate of #274

**Closed by siro20** 2017-04-06 17:01 UTC
