### ISSUE TITLE
s.t.a.l.k.e.r. shadow of chernobyl stopped to render properly on nouveau

### ISSUE THREAD

**Issue by xpue** [iXit/Mesa-3D#159] opened 2015-11-12 07:14 UTC
Works fine with nine on upstream mesa git master and on wine d3d. System: microsoft d3dx9_31.dll and d3dx9_36.dll, nouveau on gts450, gcc 5.2.0, cflags "-O0".

![a](https://drive.google.com/uc?export=download&id=0Bw8YULLJvu4gVWZhSWpoN0dDeFU)
![a](https://drive.google.com/uc?export=download&id=0Bw8YULLJvu4gOVJ5blg2eU5kbjA)
![a](https://drive.google.com/uc?export=download&id=0Bw8YULLJvu4gajFaUUE3ajBEdUk)

**Comment by iiv3** [comment] 2015-11-12 20:01
This is interesting. https://github.com/iXit/Mesa-3D/issues/80

**Comment by axeldavy** [comment] 2015-11-12 20:38
if it used to work and doesn't work anymore, the best is to do a bisect to find the bad commit, that would help a lot.

**Comment by xpue** [comment] 2015-11-12 22:38
Working mesa is upstream master, failing is generated via https://github.com/NP-Hardass/mesa-d3d9-patches/blob/master/generate-d3d9-patch.sh

**Comment by iiv3** [comment] 2015-11-13 21:13
The problem with the missing text and cursor textures is present for me too, so I did a bisect.
I landed at 
```
commit 3b5684612eafd07cf01079898cac85b57d2da700
Author: Axel Davy <axel.davy@ens.fr>
Date:   Sat May 16 14:28:41 2015 +0200
    st/nine: Add Render state validation layer
    Testing Win behaviour seems to show wrong states
    are accepted, but then the default value is used instead.
```

Reverting the patch required some manual tweaking, so I tried to circumvent `nine_check_render_state_value()` functions instead. Setting it to always return true fixes the text issues.

Permanently adding some verbosity to the debug output might be good idea. :)

**Comment by iiv3** [comment] 2015-11-13 21:29
The state with invalid value seems to be:
`nine:device9:SetRenderState: This=0x7d2a4a68 State=27(D3DRS_ALPHABLENDENABLE) Value=000000ff`

**Comment by siro20** [comment] 2015-11-15 08:02
I guess for boolean we should allow all values in nine_check_render_state_value().
Tests showed we have to apply a mask at least for some enums before checking state values.

**Comment by iiv3** [comment] 2015-11-27 02:04
Has this bug been fixed?
I don't see any new commits mentioning it.

It's known what causes it and (more or less) how to fix it.

**Comment by siro20** [comment] 2015-11-27 06:04
I'm writing tests to show windows behavior. For every enum we need a seperate tests. Once there're sufficient tests for it we can fix renderstate validation.

**Comment by iiv3** [comment] 2015-11-30 18:04
Well,  you have made and run the test for `D3DRS_ALPHABLENDENABLE` and you know the results, don't you?

I'm asking to fixing this specific bug.
You don't have to fix the whole validation code at once, you can do it in enum by enum. Start with the enum that causes this known regression.

It's been more than two weeks since the regression have been figured out. It is bad practice to keep broken code for so long.

(After the fix you can keep this issue open, or open new issue for the whole validation code).

**Comment by axeldavy** [comment] 2015-12-01 15:10
We are not full time devs, sometimes it goes fast, sometimes it goes slow. You'll have to be patient.

**Comment by axeldavy** [comment] 2015-12-01 23:37
Had time today, please test current master.

**Comment by Altosk** [comment] 2015-12-02 06:53
shadows are not being render correctly for me, can anyone confirm? also cant see the pictures anymore. Other than that everything else looked good. 
tested with gtx760.

**Comment by axeldavy** [comment] 2015-12-02 06:56
Did shadows work before yesterday's patch ?

**Comment by Altosk** [comment] 2015-12-02 06:58
i just downloaded it to test it, thats why i asked if someone else can confirm it

**Comment by xpue** [comment] 2015-12-02 11:44
Seems to work fine on gts450 with that patch.

**Comment by Altosk** [comment] 2015-12-02 15:01
maybe its a bug in nouveau with my card then?

**Comment by iiv3** [comment] 2016-03-08 20:35
I think that the original bug have been fixed and this report should be closed.
If somebody still have any issues with the game a new report should be created.

**Comment by iiv3** [comment] 2016-03-31 13:57
The original bug is fixed. I think the issue could be closed.

@Altosk, please check again your issue and open a new bug.
Have in mind, there are 3 separate d3d9 renders in STALKER, the static one does not render shadows.

**Comment by Altosk** [comment] 2016-03-31 15:22
i dont have a nvidia card anymore so i can't test if its there anymore in any case i agree with iiv3 that this should be closed if fixed.

**Closed** 2016-05-16 08:14 UTC
