### ISSUE TITLE
Alan Wake Godrays broken

### ISSUE THREAD

**Issue by LeJimster** [iXit/Mesa-3D#316] opened 2018-09-05 15:37 UTC
I wasn't sure where to leave this bug, as it happens on both vanilla wine and gallium-nine.

The godrays feature is broken in this game, left is windows, right is wine:
![alanwakegodray1](https://user-images.githubusercontent.com/35663469/45103601-2e655080-b128-11e8-8130-02b9e4b69416.jpg)
![alanwakegodray2](https://user-images.githubusercontent.com/35663469/45103605-31604100-b128-11e8-8c7c-a9154d11a01e.jpg)

[Apitrace](https://drive.google.com/open?id=1ET6N1c4Cn6L9lXjbOY9mUhfJauTY6Q4G)
[My system info](https://gist.github.com/LeJimster/7751f48f10bf0082158bace47dec7430)

**Comment by axeldavy** [comment] 2018-09-06 07:54
Are you sure gallium-nine is enabled ? Here while wine shows the issue, it works ok on nine.

**Comment by LeJimster** [comment] 2018-09-06 11:02
I just double checked it in nine and it's broken for me.  For me it looks the same in nine and vanilla wine.

**Comment by axeldavy** [comment] 2018-09-06 11:29
Have you tried to run the trace directly with nine to check if it's the 
trace vs what the game does when wine is detected ?


Which version of mesa are you using ?

**Comment by LeJimster** [comment] 2018-09-06 11:36
The trace I did was from windows, I can try attempt a trace on linux with wine/nine.

I'm using a recent mesa-git
`Mesa 18.3.0-devel (git-2c1f249f2b)`

**Comment by axeldavy** [comment] 2018-09-06 11:43
I use Ixit master, perhaps there's a commit on top of it that fixes the 
issue, I'll check mesa git.

**Comment by LeJimster** [comment] 2018-09-06 16:29
I tried replaying the trace with nine and it runs through the scene and as expected godrays is broken.  I tried the same with wine, but all I get is a black screen after the trace gets into the menus.

I have also created another trace in wine with nine enabled of the same scene if that is any help, let me know I will upload it.

**Comment by axeldavy** [comment] 2018-09-06 17:32
I bisected our repo and found the commit that fixes the issue is:
https://github.com/iXit/Mesa-3D/commit/c172f79a97c322f2bbbdb584e6b4cd903efac8a4

The commit wasn't merged into mainline mesa because it hits slightly performance, while we hadn't found any game requiring it. I guess now we have one.

**Comment by LeJimster** [comment] 2018-09-06 19:49
Shame it hits performance slightly, but if it's a small enough impact it might be worth upstreaming.  There is an Alan Wake sequel, that likely suffers the same issue (I don't have it to test).

I can try building Ixit master if you need any further testing to confirm.  Although I'm a little rusty when it comes to building/installing mesa manually.

**Closed** 2018-09-10 19:40 UTC
