### ISSUE TITLE
Missing train engines in Mashinky

### ISSUE THREAD

**Issue by hadack** [iXit/Mesa-3D#314] opened 2018-04-21 11:08 UTC
Since mesa commit ac: replace ac_build_kill with ac_build_kill_if_false the train engines in Mashinky are invisible. I tried to make an apitrace here: https://www.dropbox.com/s/ynr9v7ls561qgdw/Mashinky.6.trace?dl=0
but it crashes when replaying for me.
Maybe someone here can help me produce a working trace. I downloaded the windows build from the apitrace site and followed the instructions there.
I already opened a bug at freedesktop bugzilla:
https://bugs.freedesktop.org/show_bug.cgi?id=105333

**Comment by iiv3** [comment] 2018-04-21 21:11
@hadack,
I think it might be good idea if you fill bugreport at https://github.com/apitrace/apitrace/issues about the crash. The apitrace developer can use the same trace to reproduce it.

Give him a link to this issue too. It seems that @siro20 have located the root cause.

**Comment by siro20** [comment] 2018-04-22 07:05
@hadack : Does the game correctly render under wine (on OpenGL state tracker) ?

**Comment by hadack** [comment] 2018-04-23 11:00
Yes, it works under vanilla wine, although there is a different graphics bug in construction mode which is not there under nine. And it is noticably faster under nine.

**Comment by iiv3** [comment] 2018-07-25 23:16
@hadack, It looks like the apitrace bug might not be fixed in near future.
This is why I am looking for alternatives and I don't see many...

Do you have a working Windows installation with the Mashinky game?
It might be possible to record the game with PixWin from DXSDK_Jun10 (I think stands for June 2010).

**Comment by hadack** [comment] 2018-09-13 16:54
Hi, I fiddled a little bit around on a windows machine at work, but didn't really get something new. The apitrace seems to have the same issue as the one from wine, and I couldn't really find a lot of information about PixWin and I don't really want to install random stuff here at work...

**Comment by iiv3** [comment] 2018-09-14 13:12
PIXWin is not random, it is Microsoft program that comes from the Microsoft DirectX Software Development Kit. Newer versions got integrated into Visual Studio as "Visual Studio Graphic Diagnostic". There is also newer Pix for Windows, that works only on win64 and D3D12. Not the one we need.

You can use PixWin without installing it. You can install DXSDK_Jun10 into new `WINEPREFIX` then take the three `PIX*.*` files from `DXSDK/Utilities/bin/x86/` and copy them to your windows.

There however might be more troubles. A number of games use the function `D3DPERF_SetOptions(1)` to prevent PixWin from tracing them. I hope that this won't be the case for you. Otherwise you'd have to find the solution on your own.

---
I'm not aware of other programs that could capture D3D9 and replay it.
This means that the alternative for that is providing the game in some form.
E.g. Steam has a method to lend your games to family members. I've never used it myself, so I'm not familiar with the procedure and the perks of it. If you decide on that, you'd have to arrange it with @axeldavy as he is the most qualified to investigate the issue.

**Comment by mirh** [comment] 2018-09-14 13:50
Apitrace? Also see https://github.com/apitrace/apitrace/issues/461

Maybe some older version of nsight too.

**Comment by iiv3** [comment] 2018-09-14 17:13
> Apitrace? Also see [apitrace/apitrace#461](https://github.com/apitrace/apitrace/issues/461)

The problem is [`d3dretrace` crashes when replaying game "Mashinky" trace](https://github.com/apitrace/apitrace/issues/564). 

> Maybe some older version of nsight too.

That's NVidia one, isn't it? I would expect that it would work only with NVidia hardware, because _invidia_.

**Comment by axeldavy** [comment] 2018-09-22 21:06
So bug tracked down to texkill behaviour on NaN.

Hopefully my fix proposal on the bugzilla is accepted.

**Closed** 2018-09-23 16:43 UTC
