### ISSUE TITLE
Gallium 9 on 14.04?

### ISSUE THREAD

**Issue by vurstp** [iXit/Mesa-3D#150] opened 2015-10-27 05:10 UTC
I can't seem to install Wine on ubuntu 14.04. 
I get this error message:
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
 wine1.7 : Depends: wine1.7-i386 (= 1:1.7.52+gallium-nine~t)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

Then whenever trying to do dist-upgrade I get this:
The following packages have been kept back:
  libgbm1
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by sarnex** [comment] 2015-10-27 14:44
Are you using my PPA at https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3

**Comment by vurstp** [comment] 2015-10-27 16:34
Same error, and both dependencies are at the newest version.

vurstp@Silverback:~$ sudo apt-get install wine1.7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
 wine1.7 : Depends: wine1.7-i386 (= 1:1.7.52+gallium-nine~t)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

vurstp@Silverback:~$ sudo apt-get install libcheese-gtk23 libcheese7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcheese-gtk23 is already the newest version.
libcheese7 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by vurstp** [comment] 2015-10-27 16:41
Even using dist-upgrade this package keeps being help back:
libgbm1

When I try to install that individually I get:
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgbm1 : Depends: libgl1-mesa-dri (= 11.1+gallium-nine~git1510260800.7f6edd~gd~t)
E: Unable to correct problems, you have held broken packages.


I'm going to try doing a fresh install and a dist upgrade before I attempt to install gallium 9 + wine 1.7

**Comment by sarnex** [comment] 2015-10-27 23:50
Ok, let me know how it goes. Maybe Ubuntu updated the dependencies and I need to update wine's.

**Comment by vurstp** [comment] 2015-10-29 01:28
Following this [source](https://wiki.ixit.cz/d3d9_tutorial)
I have run this after every single step, as redundant as that may be. 
```
sudo apt-get update && sudo apt-get upgrade
sudo apt-get dist-upgrade
```
After this step, I can already see problems ahead:
```
sudo add-apt-repository ppa:oibaf/graphics-drivers
...
sudo apt-get update && sudo apt-get upgrade
...
sudo apt-get dist-upgrade
...
The following packages have been kept back:
  libgbm1
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by vurstp** [comment] 2015-10-29 02:19
Same exact issue.

**Comment by sarnex** [comment] 2015-10-29 14:00
I'll try to look into it this weekend

**Comment by sarnex** [comment] 2015-10-31 16:53
@vurstp I managed to get it to install using sudo aptitude install wine1.7, it solved the conflict

**Comment by vurstp** [comment] 2015-11-07 00:57
Thank you so much! I'll test it out when I get a chance.

**Comment by sarnex** [comment] 2015-11-19 22:11
@vurstp did you get a chance to confirm it works now?

**Comment by vurstp** [comment] 2015-11-21 04:21
It unfortunately does not work at all. In fact, running aptitude install seems to try to uninstall everything in my computer. I've tried this twice now, but running sudo aptitude install wine1.7 turns my computer into nothing but a headless ubuntu machine. Not even the network interfaces are active afterwards.

 I made an attempt to document the outputs, but after running running sudo aptitude install wine1.7 and agreeing to the changes. I could not cancel the process, nor even kill it. Pretty much everything was removed. I wish I could give you more information but I would have to try it a third time - and I shall, now that I know how to record what happened.

**Comment by sarnex** [comment] 2015-11-21 15:25
@vurstp Wow, very strange. I ran aptitude with a fresh ubuntu install and it installed fine. I'm not sure how to reproduce this. If you find a way let me know and I'll try to fix it

**Comment by vurstp** [comment] 2015-12-20 05:53
family@Silverback:~$ sudo apt-get install aptitude && sudo aptitude install wine1.7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-3.19.0-25 linux-headers-3.19.0-25-generic
  linux-image-3.19.0-25-generic linux-image-extra-3.19.0-25-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  aptitude-common libboost-iostreams1.54.0 libcwidget3 libept1.4.12
Suggested packages:
  aptitude-doc-en aptitude-doc tasksel debtags libcwidget-dev
The following NEW packages will be installed:
  aptitude aptitude-common libboost-iostreams1.54.0 libcwidget3 libept1.4.12
0 upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
Need to get 2,549 kB of archives.
After this operation, 10.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] 

open: 208; closed: 1535; defer: 67; conflict: 92                               oThe following actions will resolve these dependencies:

      Remove the following packages:                                            
1)      account-plugin-aim                                                      
2)      account-plugin-facebook                                                 
3)      account-plugin-flickr                                                   
4)      account-plugin-google                                                   
5)      account-plugin-jabber                                                   
6)      account-plugin-salut                                                    
7)      account-plugin-twitter                                                  
8)      account-plugin-yahoo                                                    
9)      appmenu-qt5                                                             
10)     checkbox-gui                                                            
11)     cheese                                                                  
12)     chrome-token-signing                                                    
13)     empathy                                                                 
14)     estonianidcard                                                          
15)     friends-facebook                                                        
16)     friends-twitter                                                         
17)     gir1.2-totem-1.0                                                        
18)     gnome-contacts                                                          
19)     gstreamer1.0-clutter                                                    
20)     hud                                                                     
21)     indicator-bluetooth                                                     
22)     libaccount-plugin-generic-oauth                                         
23)     libaccount-plugin-google                                                
24)     libcheese-gtk23                                                         
25)     libcheese7                                                              
26)     libclutter-1.0-0                                                        
27)     libclutter-gst-2.0-0                                                    
28)     libclutter-gtk-1.0-0                                                    
29)     libcogl-pango15                                                         
30)     libcogl15                                                               
31)     libgbm1                                                                 
32)     liboxideqt-qmlplugin                                                    
33)     liboxideqtcore0                                                         
34)     liboxideqtquick0                                                        
35)     libqt5feedback5                                                         
36)     libqt5gui5                                                              
37)     libqt5multimedia5                                                       
38)     libqt5opengl5                                                           
39)     libqt5printsupport5                                                     
40)     libqt5quick5                                                            
41)     libqt5svg5                                                              
42)     libqt5webkit5                                                           
43)     libqt5webkit5-qmlwebkitplugin                                           
44)     libqt5widgets5                                                          
45)     libtotem0                                                               
46)     libunity-webapps0                                                       
47)     mcp-account-manager-uoa                                                 
48)     nautilus-sendto-empathy                                                 
49)     qdigidoc                                                                
50)     qesteidutil                                                             
51)     qtdeclarative5-accounts-plugin                                          
52)     qtdeclarative5-dialogs-plugin                                           
53)     qtdeclarative5-privatewidgets-plugin                                    
54)     qtdeclarative5-qtfeedback-plugin                                        
55)     qtdeclarative5-qtquick2-plugin                                          
56)     qtdeclarative5-ubuntu-ui-extras-browser-plugin                          
57)     qtdeclarative5-ubuntu-ui-toolkit-plugin                                 
58)     qtdeclarative5-window-plugin                                            
59)     signon-plugin-oauth2                                                    
60)     signon-ui                                                               
61)     totem                                                                   
62)     totem-mozilla                                                           
63)     totem-plugins                                                           
64)     ubuntu-desktop                                                          
65)     unity-control-center                                                    
66)     unity-control-center-signon                                             
67)     unity-scope-gdrive                                                      
68)     unity-webapps-common                                                    
69)     unity-webapps-qml                                                       
70)     unity-webapps-service                                                   
71)     webaccounts-extension-common                                            
72)     webapp-container                                                        
73)     webbrowser-app                                                          
74)     xul-ext-unity                                                           
75)     xul-ext-webaccounts                                                     
76)     xul-ext-websites-integration                                            

      Keep the following packages at their current version:                     
77)     libegl1-mesa:i386 [Not Installed]                                       
78)     libgbm1:i386 [Not Installed]                                            
79)     libgl1-mesa-dri [Not Installed]                                         
80)     libgl1-mesa-dri:i386 [Not Installed]                                    
81)     libglapi-mesa [Not Installed]                                           
82)     libglapi-mesa:i386 [Not Installed]                                      
83)     libosmesa6 [Not Installed]                                              
84)     libosmesa6:i386 [Not Installed]                                         
85)     wine1.7 [Not Installed]                                                 
86)     wine1.7-amd64 [Not Installed]                                           
87)     wine1.7-i386:i386 [Not Installed]                                       

      Leave the following dependencies unresolved:                              
88)     friends-dispatcher recommends friends-facebook                          
89)     friends-dispatcher recommends friends-twitter                           
90)     indicator-appmenu recommends appmenu-qt5                                
91)     indicator-datetime recommends unity-control-center (>= 14.04.3) | ubuntu
92)     indicator-power recommends unity-control-center | gnome-control-center (
93)     indicator-sound recommends unity-control-center | gnome-control-center |
94)     libaccount-plugin-1.0-0 recommends unity-control-center-signon          
95)     signond recommends signon-ui                                            
96)     ubuntu-desktop recommends cheese                                        
97)     ubuntu-desktop recommends empathy                                       
98)     ubuntu-desktop recommends totem                                         
99)     ubuntu-desktop recommends totem-mozilla                                 
100     unity-lens-files recommends unity-scope-gdrive                          
101     unity-lens-photos recommends account-plugin-flickr                      
102     unity-lens-photos recommends account-plugin-google                      
103     unity-lens-photos recommends account-plugin-facebook                    
104     winetricks recommends wine                                              
105     empathy recommends gnome-contacts                                       
106     gnome-bluetooth recommends unity-control-center | gnome-control-center  
107     indicator-session recommends unity-control-center | gnome-control-center
108     indicator-session recommends unity-control-center-signon | gnome-control
109     libhud2 recommends hud (= 14.04+14.04.20140604-0ubuntu1)                
110     mcp-account-manager-uoa recommends account-plugin-aim                   
111     mcp-account-manager-uoa recommends account-plugin-jabber                
112     mcp-account-manager-uoa recommends account-plugin-google                
113     mcp-account-manager-uoa recommends account-plugin-yahoo                 
114     mcp-account-manager-uoa recommends account-plugin-salut                 
115     unity recommends unity-control-center                                   
116     unity recommends unity-scope-gdrive                                     
117     unity recommends indicator-bluetooth                                    
118     unity recommends hud                                                    
119     gnome-panel recommends unity-control-center                             


Accept this solution? [Y/n/q/?] 

(Reading database ... 233477 files and directories currently installed.)
Removing account-plugin-aim (3.8.6-0ubuntu9.2) ...
Removing friends-facebook (0.2.0+14.04.20140217.1-0ubuntu1) ...
Removing account-plugin-facebook (0.11+14.04.20140409.1-0ubuntu2) ...
Removing account-plugin-flickr (0.11+14.04.20140409.1-0ubuntu2) ...
Removing unity-scope-gdrive (0.9+13.10.20130723-0ubuntu1) ...
Removing account-plugin-google (0.11+14.04.20140409.1-0ubuntu2) ...
Removing account-plugin-jabber (3.8.6-0ubuntu9.2) ...
Removing account-plugin-salut (3.8.6-0ubuntu9.2) ...
Removing friends-twitter (0.2.0+14.04.20140217.1-0ubuntu1) ...
Removing account-plugin-twitter (0.11+14.04.20140409.1-0ubuntu2) ...
Removing account-plugin-yahoo (3.8.6-0ubuntu9.2) ...
Removing appmenu-qt5 (0.3.0+14.04.20140415-0ubuntu1) ...
Removing ubuntu-desktop (1.325) ...
Removing checkbox-gui (0.17.6-0ubuntu6) ...
Removing checkbox-ng-service (0.3-2) ...
Removing checkbox-ng (0.3-2) ...
Removing cheese (3.10.2-0ubuntu2) ...
Removing estonianidcard (3.10.2.1573-1404) ...
Removing chrome-token-signing (1:1.0.0.388-1404) ...
Removing nautilus-sendto-empathy (3.8.6-0ubuntu9.2) ...
Removing mcp-account-manager-uoa (3.8.6-0ubuntu9.2) ...
Removing empathy (3.8.6-0ubuntu9.2) ...
Removing empathy-common (3.8.6-0ubuntu9.2) ...
Removing gnome-contacts (3.8.3-1ubuntu1) ...
Removing libfolks-telepathy25:amd64 (0.9.5-1ubuntu5) ...
Removing libfolks-eds25:amd64 (0.9.5-1ubuntu5) ...
Removing libfolks25:amd64 (0.9.5-1ubuntu5) ...
Removing folks-common (0.9.5-1ubuntu5) ...
Removing totem-plugins (3.10.1-1ubuntu4) ...
Removing gir1.2-totem-1.0 (3.10.1-1ubuntu4) ...
Removing gnome-video-effects (0.4.1-0ubuntu1) ...
Removing telepathy-haze (0.8.0-1) ...
Removing libpurple0 (1:2.10.9-0ubuntu3.2) ...
Removing libfarstream-0.1-0:amd64 (0.1.2-1ubuntu3) ...
Removing gstreamer0.10-nice:amd64 (0.1.4-1) ...
Removing totem-mozilla (3.10.1-1ubuntu4) ...
Removing totem (3.10.1-1ubuntu4) ...
Removing xul-ext-webaccounts (0.5-0ubuntu2.14.04.1) ...
Removing webaccounts-extension-common (0.5-0ubuntu2.14.04.1) ...
Removing unity-control-center-signon (0.1.7~+14.04.20140211.2-0ubuntu4) ...
Removing libtelepathy-farstream3:amd64 (0.6.1-0ubuntu1) ...
Removing libfarstream-0.2-2:amd64 (0.2.3-1ubuntu2) ...
Removing gstreamer1.0-nice:amd64 (0.1.4-1) ...
Removing hud (14.04+14.04.20140604-0ubuntu1) ...
Removing libaccount-plugin-generic-oauth (0.11+14.04.20140409.1-0ubuntu2) ...
Removing libaccount-plugin-google (0.11+14.04.20140409.1-0ubuntu2) ...
Removing telepathy-salut (0.8.1-1ubuntu3) ...
Removing libavahi-gobject0:amd64 (0.6.31-4ubuntu1) ...
Removing libtotem0 (3.10.1-1ubuntu4) ...
Removing qesteidutil (3.10.1.1187-1404) ...
Removing qdigidoc (3.11.1.1426-1404) ...
Removing telepathy-gabble (0.18.3-0ubuntu0.1) ...
Removing libnice10:amd64 (0.1.4-1) ...
Removing libgupnp-igd-1.0-4:amd64 (0.2.2-1) ...
Removing unity-webapps-common (2.4.17+14.04.20140416-0ubuntu1) ...
Removing xul-ext-unity (3.0.0+14.04.20140416-0ubuntu1.14.04.1) ...
Removing xul-ext-websites-integration (2.3.6+13.10.20130920.1-0ubuntu1.2) ...
Removing libmeanwhile1 (1.0.2-4.1ubuntu1) ...
Removing telepathy-mission-control-5 (1:5.16.1-1ubuntu3) ...
Removing libmission-control-plugins0 (1:5.16.1-1ubuntu3) ...
Removing libpurple-bin (1:2.10.9-0ubuntu3.2) ...
Removing signon-plugin-oauth2 (0.19+14.04.20140305-0ubuntu2) ...
Removing signon-ui (0.16+14.04.20140304.is.0.15+14.04.20140313-0ubuntu1) ...
Removing telepathy-logger (0.8.0-3) ...
Removing libtelepathy-logger3:amd64 (0.8.0-3) ...
Removing libufe-xidgetter0 (3.0.0+14.04.20140416-0ubuntu1.14.04.1) ...
Removing libzephyr4:amd64 (3.1.2-1) ...
Removing plainbox-provider-checkbox (0.4-1) ...
Removing plainbox-provider-resource-generic (0.3-1) ...
Removing python3-checkbox-ng (0.3-2) ...
Removing python3-plainbox (0.5.3-2) ...
Removing plainbox-secure-policy (0.5.3-2) ...
Removing python3-checkbox-support (0.2-1) ...
Removing python3-pyparsing (2.0.1+dfsg1-1build1) ...
Removing python3-requests (2.2.1-1ubuntu0.3) ...
Removing python3-urllib3 (1.7.1-1ubuntu4) ...
Removing qtdeclarative5-localstorage-plugin:amd64 (5.2.1-3ubuntu15.1) ...
Removing signon-plugin-password (8.56+14.04.20140307-0ubuntu2) ...
Removing libunity-webapps0 (2.5.0~+14.04.20140409-0ubuntu1) ...
Removing unity-webapps-service (2.5.0~+14.04.20140409-0ubuntu1) ...
Removing webapp-container (0.23+14.04.20140428-0ubuntu1) ...
Removing webbrowser-app (0.23+14.04.20140428-0ubuntu1) ...
Removing qtdeclarative5-ubuntu-ui-extras-browser-plugin:amd64 (0.23+14.04.20140428-0ubuntu1) ...
Removing unity-webapps-qml (0.1+14.04.20140408-0ubuntu1) ...
Removing liboxideqt-qmlplugin:amd64 (1.11.3-0ubuntu0.14.04.1) ...
Removing liboxideqtquick0:amd64 (1.11.3-0ubuntu0.14.04.1) ...
Removing liboxideqtcore0:amd64 (1.11.3-0ubuntu0.14.04.1) ...
Removing qtdeclarative5-ubuntu-ui-toolkit-plugin:amd64 (0.1.46+14.04.20140408.1-0ubuntu1) ...
Removing qtdeclarative5-qtfeedback-plugin:amd64 (5.0~git20130529-0ubuntu3) ...
Removing libqt5feedback5:amd64 (5.0~git20130529-0ubuntu3) ...
Removing libqt5multimedia5:amd64 (5.2.1-0ubuntu5) ...
Removing libqt5webkit5-qmlwebkitplugin:amd64 (5.1.1-1ubuntu8) ...
Removing libqt5webkit5:amd64 (5.1.1-1ubuntu8) ...
Removing libqt5opengl5:amd64 (5.2.1+dfsg-1ubuntu14.3) ...
Removing libqt5organizer5:amd64 (5.0~git20140203~e0c5eebe-0ubuntu2) ...
Removing libqt5printsupport5:amd64 (5.2.1+dfsg-1ubuntu14.3) ...
Removing libqt5qml-graphicaleffects:amd64 (5.2.1-1) ...
Removing qtdeclarative5-window-plugin:amd64 (5.2.1-3ubuntu15.1) ...
Removing qtdeclarative5-accounts-plugin (0.4+14.04.20140317-0ubuntu1) ...
Removing qtdeclarative5-qtquick2-plugin:amd64 (5.2.1-3ubuntu15.1) ...
Removing libqt5svg5:amd64 (5.2.1-1) ...
Removing qtdeclarative5-dialogs-plugin:amd64 (5.2.1-3ubuntu15.1) ...
Removing qtdeclarative5-privatewidgets-plugin:amd64 (5.2.1-3ubuntu15.1) ...
Removing libqt5widgets5:amd64 (5.2.1+dfsg-1ubuntu14.3) ...
Removing libthumbnailer0:amd64 (1.1+14.04.20150205-0ubuntu1) ...
Removing qtdeclarative5-ubuntu-ui-extras-browser-plugin-assets (0.23+14.04.20140428-0ubuntu1) ...
Removing ubuntu-ui-toolkit-theme (0.1.46+14.04.20140408.1-0ubuntu1) ...
Removing indicator-bluetooth (0.0.6+14.04.20140207-0ubuntu2) ...
Removing qtdeclarative5-unity-action-plugin:amd64 (1.1.0+14.04.20140304-0ubuntu1) ...
Removing libunity-action-qt1:amd64 (1.1.0+14.04.20140304-0ubuntu1) ...
Removing libhud2:amd64 (14.04+14.04.20140604-0ubuntu1) ...
Removing libqt5quick5:amd64 (5.2.1-3ubuntu15.1) ...
Removing unity-control-center (14.04.3+14.04.20150916-0ubuntu1) ...
Removing libcheese-gtk23:amd64 (3.10.2-0ubuntu2) ...
Removing libclutter-gtk-1.0-0:amd64 (1.4.4-3ubuntu2.2) ...
Removing libqt5gui5:amd64 (5.2.1+dfsg-1ubuntu14.3) ...
Removing libcheese7:amd64 (3.10.2-0ubuntu2) ...
Removing gstreamer1.0-clutter (2.0.8-1build1) ...
Removing libclutter-gst-2.0-0:amd64 (2.0.8-1build1) ...
Removing libclutter-1.0-0:amd64 (1.16.4-0ubuntu2) ...
Removing libcogl-pango15:amd64 (1.16.2-1) ...
Removing libcogl15:amd64 (1.16.2-1) ...
Removing libgbm1:amd64 (10.1.3-0ubuntu0.5) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Processing triggers for gconf2 (3.2.6-0ubuntu2) ...
Processing triggers for libglib2.0-0:i386 (2.40.2-0ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.40.2-0ubuntu1) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...

reboot and then:

open: 93; closed: 521; defer: 24; conflict: 31                                 .The following actions will resolve these dependencies:

      Keep the following packages at their current version:
1)      libegl1-mesa:i386 [Not Installed]                  
2)      libgbm1:i386 [Not Installed]                       
3)      libgl1-mesa-dri:i386 [Not Installed]               
4)      libglapi-mesa [Not Installed]                      
5)      libglapi-mesa:i386 [Not Installed]                 
6)      libosmesa6 [Not Installed]                         
7)      libosmesa6:i386 [Not Installed]                    
8)      wine1.7 [Not Installed]                            
9)      wine1.7-amd64 [Not Installed]                      
10)     wine1.7-i386:i386 [Not Installed]                  

      Leave the following dependencies unresolved:         
11)     winetricks recommends wine                         


Accept this solution? [Y/n/q/?] 

Reboot again and then when I run:
WINEPREFIX=$HOME/prefix32 WINEARCH='win32' winecfg

I get:
The program 'winecfg' is currently not installed. You can install it by typing:
sudo apt-get install wine1.6

At this point my Settings is gone, and some of my installed programs are gone. The last time I tried this, I kept retrying 'sudo apt-get install aptitude && sudo aptitude install wine1.7' and wound up with nothing but a terminal prompt.

**Comment by vurstp** [comment] 2015-12-20 21:52
So I found out that it's not installing aptitude that causes this, it's trying to use aptitude to install wine1.7. 
Why is it trying to resolve dependency conflicts while simultaneously never install wine, I have no idea. This is on a fresh install of ubuntu 14.04

**Comment by sarnex** [comment] 2015-12-23 21:38
Very strange. Using aptitude resolved the issue on a fresh 14.04 image when
I last tried. I'm not sure what the correct solution is here.

**Comment by vurstp** [comment] 2015-12-25 04:49
I've been trying this on the same machine. It might be related to hardware somehow, but I don't know how that would be the case.

**Comment by vurstp** [comment] 2015-12-28 05:15
I think I know why now I have issues:

```
Supported Ubuntu versions:
- 14.04 (trusty) <- only 14.04 and 14.04.1 are supported. 14.04.2 and later are not supported
- 15.04 (vivid)
- 15.10 (wily) <- recommended for this PPA
```
[Source](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers)

Guess what I'm doing fresh installs with:
```
:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

I hate to be a pain, but maybe this kind of information should also be incorporated into the [tutorial](https://wiki.ixit.cz/d3d9_tutorial)

Given this information, I wonder if at all using aptitude to install wine1.7 is necessary. 

Will give it a shot in the next couple of days.

**Comment by sarnex** [comment] 2015-12-28 14:33
Ok, I don't know if it matters but since it's a requirement of the oibaf
ppa I will add it.

**Comment by sarnex** [comment] 2016-01-04 15:15
@vurstp Try sudo apt-get install wine1.8, I updated my PPA.

**Comment by axeldavy** [comment] 2018-09-15 17:46
As 14.04 is deprecated, I close this issue.

**Closed by axeldavy** 2018-09-15 17:46 UTC
