### ISSUE TITLE
[nine] Down of War 2 does not start with shadows enabled

### ISSUE THREAD

**Issue by pontostroy** [iXit/Mesa-3D#230] opened 2016-09-02 11:11 UTC
Ixit master git 2016 09 02
Radeon hd 7970

```
nine:surface9:LockRect: returning system memory
nine:surface9:AddDirtyRect: This=0xd9cf8930 box=0x33f488
nine:texture9:AddDirtyRect: This=0xda113de8 pDirtyRect=0x33f478[(0,0)-(8,8)]
nine:surface9:UnlockRect: This=0xd9cf8930 lock_count=1
nine:surface9:LockRect: This=0xd9cf8a40 pLockedRect=0x33f528 pRect=(nil)[0..0,0..0] Flags=NOSYSLOCK|
nine:surface9:Dump: 
NineSurface9(0xd9cf8a40->(nil)/0xda113f30): Pool=MANAGED Type=SURFACE Usage=
Dims=2x2 Format=D3DFMT_DXT5 Stride=16 Lockable=0
Level=2(2), Layer=0
nine:unknown:QueryInterface: This=0xda113de8 riid=0x33f3ec ppvObject=0x33f3e8
nine:basetexture9:Dump: 
NineBaseTexture9(0xda113de8->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_DXT5 Dims=8x8x1/1 LastLevel=3 Lod=0(4294967295)
nine:surface9:LockRect: returning system memory
nine:surface9:AddDirtyRect: This=0xd9cf8a40 box=0x33f488
nine:texture9:AddDirtyRect: This=0xda113de8 pDirtyRect=0x33f478[(0,0)-(8,8)]
nine:surface9:UnlockRect: This=0xd9cf8a40 lock_count=1
nine:surface9:LockRect: This=0xd9cf8b50 pLockedRect=0x33f528 pRect=(nil)[0..0,0..0] Flags=NOSYSLOCK|
nine:surface9:Dump: 
NineSurface9(0xd9cf8b50->(nil)/0xda113f40): Pool=MANAGED Type=SURFACE Usage=
Dims=1x1 Format=D3DFMT_DXT5 Stride=16 Lockable=0
Level=3(3), Layer=0
nine:unknown:QueryInterface: This=0xda113de8 riid=0x33f3ec ppvObject=0x33f3e8
nine:basetexture9:Dump: 
NineBaseTexture9(0xda113de8->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_DXT5 Dims=8x8x1/1 LastLevel=3 Lod=0(4294967295)
nine:surface9:LockRect: returning system memory
nine:surface9:AddDirtyRect: This=0xd9cf8b50 box=0x33f488
nine:texture9:AddDirtyRect: This=0xda113de8 pDirtyRect=0x33f478[(0,0)-(8,8)]
nine:surface9:UnlockRect: This=0xd9cf8b50 lock_count=1
nine:device9:SetViewport: X=0 Y=0 W=1920 H=1080 MinZ=0.000000 MaxZ=1.000000
nine:device9:SetScissorRect: x=(0..0) y=(1920..1080)
nine:device9:BeginScene: This=0xf18a92c0
nine:device9:SetRenderTarget: This=0xf18a92c0 RenderTargetIndex=0 pRenderTarget=0xf192bd70
nine:device9:Clear: This=0xf18a92c0 Count=1 pRects=0x33fc74 Flags=1 Color=ff000000 Z=1.000000 Stencil=0
nine:update_framebuffer: 
nine:device9:Clear: First rect covers viewport.
nine:device9:Clear: Clear fast path
nine:device9:SetRenderTarget: This=0xf18a92c0 RenderTargetIndex=0 pRenderTarget=0xf192bd70
nine:unknown:QueryInterface: This=0xf1933ae0 riid=0x19b18e0 ppvObject=0x33faf8
nine:device9:SetDepthStencilSurface: This=0xf18a92c0 pNewZStencil=0xf1933ae0
nine:device9:SetRenderTarget: This=0xf18a92c0 RenderTargetIndex=0 pRenderTarget=0xe83a83d8
nine:unknown:QueryInterface: This=0xe83a8790 riid=0x19b18e0 ppvObject=0x33f908
iunknown.c:71:NineUnknown_QueryInterface: Assertion `This->refs' failed.
wine: Unhandled exception 0x80000003 in thread 6f at address 0xf642022d (thread 006f), starting debugger...
fixme:ntdll:EtwEventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x10077580, 0x100ed0e0, 0x100ed0d8
fixme:ntdll:EtwEventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x10077580, 0x100ed118, 0x100ed110
fixme:ntdll:EtwEventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x10077580, 0x100ed0a8, 0x100ed0a0
fixme:ntdll:EtwEventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x10077580, 0x100ed150, 0x100ed148
fixme:ntdll:EtwEventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x10077580, 0x100ed188, 0x100ed180
fixme:imm:ImmGetOpenStatus (0x156830): semi-stub
fixme:ver:GetCurrentPackageId (0x33f01c (nil)): stub
0xf642022d: int $3
```

**Comment by siro20** [comment] 2016-09-10 18:12
I had the same error while trying to capture a trace using apitrace. Removing the assert allowed me to continue as normal. I'll investigate if the assert is correct.

**Comment by axeldavy** [comment] 2016-09-13 21:17
The Sims 2 hits the assert as well, and runs fine if removed.

**Comment by siro20** [comment] 2016-09-14 17:49
The problem is easy to reproduce:
* Create a texture
* Call GetSurfaceLevel to get the surface
* Call QueryInterface pointing the surface itself

The assert will fail as the surface does forward it's refcount to container (texture).

**Comment by axeldavy** [comment] 2016-09-26 20:07
Here it is (and I added debug info)

`nine:device9:CreateTexture: This=0x7c38d7d8 Width=1 Height=1 Levels=1 Usage= Format=D3DFMT_A4R4G4B4 Pool=MANAGED ppOut=0x33eb7c pSharedHandle=(nil)
nine:texture9:ctor: (0x6907d1c0) Width=1 Height=1 Levels=1 Usage= Format=D3DFMT_A4R4G4B4 Pool=MANAGED pSharedHandle=(nil)
nine:basetexture9:ctor: This=0x6907d1c0, pParams=0x33ea28 initResource=(nil) Type=3 format=26 Pool=1 Usage=0
nine:resource9:ctor: This=0x6907d1c0 pParams=0x33ea28 initResource=(nil) Allocate=0 Type=3 Pool=1 Usage=0
nine:unknown:AddRef: This=0x7c38d7d8 refs:1676, forward:0, bind: 0, device=(nil), container=(nil)
nine:unknown:ctor: This=0x6907d1c0 refs:1, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:surface9:ctor: This=0x690626e8 pDevice=0x7c38d7d8 pResource=(nil) Level=0 Layer=0 pDesc=0x33e9ac
nine:resource9:ctor: This=0x690626e8 pParams=0x33e8f8 initResource=(nil) Allocate=0 Type=1 Pool=1 Usage=0
nine:unknown:ctor: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:surface9:Dump: 
NineSurface9(0x690626e8->(nil)/0x6907d2a0): Pool=MANAGED Type=SURFACE Usage=
Dims=1x1 Format=D3DFMT_A4R4G4B4 Stride=4 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x6907d1c0 riid=0x33e7fc id={580CA87E,1D3C,4D54,991DB7D3E3C298CE} ppvObject=0x33e7f8
nine:unknown:QueryInterface: This=0x6907d1c0 refs:1, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x6907d1c0 refs:1, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:basetexture9:Dump: 
NineBaseTexture9(0x6907d1c0->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A4R4G4B4 Dims=1x1x1/1 LastLevel=0 Lod=0(4294967295)
nine:unknown:Release: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:basetexture9:GetLevelCount: This=0x6907d1c0
nine:texture9:GetSurfaceLevel: This=0x6907d1c0 Level=0 pDesc=0x33ebbc
nine:unknown:AddRef: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:unknown:AddRef: This=0x6907d1c0 refs:1, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:unknown:AddRef: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:unknown:AddRef: This=0x6907d1c0 refs:3, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:Release: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:unknown:Release: This=0x6907d1c0 refs:4, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:Release: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:unknown:Release: This=0x6907d1c0 refs:3, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33eb30
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33ead4
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33ead4
nine:basetexture9:GetLOD: This=0x6907d1c0
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33eb10
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33eb30
nine:unknown:Release: This=0x6907d1c0 refs:3, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:surface9:LockRect: This=0x690626e8 pLockedRect=0x33eb60 pRect=(nil)[0..0,0..0] Flags=NOSYSLOCK|
nine:surface9:Dump: 
NineSurface9(0x690626e8->(nil)/0x6907d2a0): Pool=MANAGED Type=SURFACE Usage=
Dims=1x1 Format=D3DFMT_A4R4G4B4 Stride=4 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x6907d1c0 riid=0x33ea7c id={580CA87E,1D3C,4D54,991DB7D3E3C298CE} ppvObject=0x33ea78
nine:unknown:QueryInterface: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:basetexture9:Dump: 
NineBaseTexture9(0x6907d1c0->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A4R4G4B4 Dims=1x1x1/1 LastLevel=0 Lod=0(4294967295)
nine:unknown:Release: This=0x6907d1c0 refs:3, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:surface9:LockRect: returning system memory
nine:unknown:QueryInterface: This=0x6907d1c0 riid=0x73246030 id={580CA87E,1D3C,4D54,991DB7D3E3C298CE} ppvObject=0x33ea98
nine:unknown:QueryInterface: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:Release: This=0x6907d1c0 refs:3, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:surface9:AddDirtyRect: This=0x690626e8 box=0x33eaf4
nine:unknown:QueryInterface: This=0x6907d1c0 riid=0x73245f50 id={85C31227,3DE5,4F00,9B3AF11AC38C18B5} ppvObject=0x33eae0
nine:unknown:QueryInterface: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:unknown:AddRef: This=0x6907d1c0 refs:2, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:texture9:AddDirtyRect: This=0x6907d1c0 pDirtyRect=0x33eae4[(0,0)-(1,1)]
nine:unknown:Release: This=0x6907d1c0 refs:3, forward:0, bind: 0, device=0x7c38d7d8, container=(nil)
nine:surface9:UnlockRect: This=0x690626e8 lock_count=1
nine:device9:SetTexture: This=0x7c38d7d8 Stage=0 pTexture=0x6907d1c0
nine:device9:SetTextureStageState: Stage=0 Type=11 Value=00020000
nine:nine_dump_D3DTSS_value: D3DTSS_TEXCOORDINDEX = CAMERASPACEPOSITION 0
nine:device9:SetTextureStageState: Stage=1 Type=11 Value=00020000
nine:nine_dump_D3DTSS_value: D3DTSS_TEXCOORDINDEX = CAMERASPACEPOSITION 0
nine:device9:SetTextureStageState: Stage=0 Type=24 Value=00000104
nine:nine_dump_D3DTSS_value: D3DTSS_TEXTURETRANSFORMFLAGS = (D3DTTFF_?)
nine:device9:SetTextureStageState: Stage=1 Type=24 Value=00000104
nine:nine_dump_D3DTSS_value: D3DTSS_TEXTURETRANSFORMFLAGS = (D3DTTFF_?)
nine:device9:SetTransform: This=0x7c38d7d8 State=16 pMatrix=0x1937068
nine:device9:SetTransform: This=0x7c38d7d8 State=17 pMatrix=0x19370a8
nine:device9:SetRenderTarget: This=0x7c38d7d8 RenderTargetIndex=0 pRenderTarget=0x7c256140
nine:device9:SetDepthStencilSurface: This=0x7c38d7d8 pNewZStencil=(nil)
nine:device9:Clear: This=0x7c38d7d8 Count=0 pRects=(nil) Flags=1 Color=6d6d6d68 Z=0.000000 Stencil=0
nine:basetexture9:Validate: This=0x6907d1c0 dirty=1 dirty_mip=0 lod=0/4294967295
nine:basetexture9:UploadSelf: This=0x6907d1c0 dirty=1 type=TEXTURE
nine:basetexture9:UploadSelf: updating LOD from 4294967295 to 0 ...
nine:basetexture9:CreatePipeResource: This=0x6907d1c0 lod=0 last_level=0
nine:surface9:UploadSelf: This=0x690626e8 damaged=0x33ea24
nine:basetexture9:UploadSelf: DONE, generate mip maps = 0
nine:basetexture9:Validate: This=0x6b1c0da8 dirty=1 dirty_mip=0 lod=0/4294967295
nine:basetexture9:UploadSelf: This=0x6b1c0da8 dirty=1 type=TEXTURE
nine:basetexture9:UploadSelf: updating LOD from 4294967295 to 0 ...
nine:basetexture9:CreatePipeResource: This=0x6b1c0da8 lod=0 last_level=2
nine:surface9:UploadSelf: This=0x6b1c0f38 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c1048 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c1158 damaged=0x33ea24
nine:basetexture9:UploadSelf: DONE, generate mip maps = 0
nine:basetexture9:Validate: This=0x6b1c0348 dirty=1 dirty_mip=0 lod=0/4294967295
nine:basetexture9:UploadSelf: This=0x6b1c0348 dirty=1 type=TEXTURE
nine:basetexture9:UploadSelf: updating LOD from 4294967295 to 0 ...
nine:basetexture9:CreatePipeResource: This=0x6b1c0348 lod=0 last_level=8
nine:surface9:UploadSelf: This=0x6b1c0418 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0528 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0638 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0748 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0858 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0968 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0a78 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0b88 damaged=0x33ea24
nine:surface9:UploadSelf: This=0x6b1c0c98 damaged=0x33ea24
nine:basetexture9:UploadSelf: DONE, generate mip maps = 0
nine:update_framebuffer: 
nine:device9:Clear: Clear fast path
nine:surface9:LockRect: This=0x7c256140 pLockedRect=0x33ebe4 pRect=(nil)[0..0,0..0] Flags=NOSYSLOCK|
nine:surface9:Dump: 
NineSurface9(0x7c256140->0x7bd2fbd8/(nil)): Pool=DEFAULT Type=SURFACE Usage=RT
Dims=16x16 Format=D3DFMT_X8R8G8B8 Stride=64 Lockable=0
Level=0(0), Layer=0
nine:surface9:LockRect: mapping pipe_resource 0x7bd2fbd8 (level=0 usage=3)
nine:surface9:AddDirtyRect: This=0x7c256140 box=0x33eb84
nine:surface9:UnlockRect: This=0x7c256140 lock_count=1
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33ebcc
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33eb70
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33eb70
nine:basetexture9:GetLOD: This=0x6907d1c0
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33ebac
nine:texture9:GetLevelDesc: This=0x6907d1c0 Level=0 pDesc=0x33ebcc
nine:unknown:Release: This=0x690626e8 refs:0, forward:1, bind: 0, device=0x7c38d7d8, container=0x6907d1c0
nine:unknown:Release: This=0x6907d1c0 refs:2, forward:0, bind: 1, device=0x7c38d7d8, container=(nil)
nine:unknown:Release: This=0x6907d1c0 refs:1, forward:0, bind: 1, device=0x7c38d7d8, container=(nil)
nine:unknown:Release: This=0x7c38d7d8 refs:1677, forward:0, bind: 0, device=(nil), container=(nil)
nine:device9:SetVertexDeclaration: This=0x7c38d7d8 pDecl=0x6b1c1268
nine:device9:SetStreamSource: This=0x7c38d7d8 StreamNumber=0 pStreamData=0x7bd32de8 OffsetInBytes=0 Stride=12
nine:device9:SetIndices: This=0x7c38d7d8 pIndexData=0x7bd7b328
nine:device9:SetRenderTarget: This=0x7c38d7d8 RenderTargetIndex=0 pRenderTarget=0x7c250f40
nine:device9:SetDepthStencilSurface: This=0x7c38d7d8 pNewZStencil=0x7bd2e480
nine:unknown:QueryInterface: This=0x6907d1c0 riid=0xf4a3fc id={85C31227,3DE5,4F00,9B3AF11AC38C18B5} ppvObject=0x33ec78
nine:unknown:QueryInterface: This=0x6907d1c0 refs:0, forward:0, bind: 1, device=0x7c38d7d8, container=(nil)
../../../../../../../mesa_src_d3d9/Mesa-3D/src/gallium/state_trackers/nine/iunknown.c:89:NineUnknown_QueryInterface: Assertion `This->forward || This->refs' failed.
nine:unknown:Release: This=0x6907d1c0 refs:0, forward:0, bind: 1, device=0x7c38d7d8, container=(nil)`

**Comment by axeldavy** [comment] 2016-09-26 20:09
It seems the texture has no more reference, but is not destroyed because it is bound as texture.

**Comment by axeldavy** [comment] 2016-09-26 20:14
The app is not happy If I return D3DERR_INVALIDCALL in that case. I guess we have to accept it.

**Comment by siro20** [comment] 2016-09-27 16:54
were does that call come from: nine:unknown:QueryInterface: This=0x6907d1c0 riid=0xf4a3fc id={85C31227,3DE5,4F00,9B3AF11AC38C18B5} ppvObject=0x33ec78 ? does the app query the interface ?

**Comment by axeldavy** [comment] 2016-09-27 18:56
Yes, that's the failing call.

**Comment by siro20** [comment] 2016-09-27 20:04
According to the spec the behavior is undefined. It might return E_NOINTERFACE in case the refcount is zero.

**Comment by siro20** [comment] 2016-09-28 16:19
I've did some tests on Windows and Wine. Both think it's OK to return the interface as long as the object is alive (as long as refs > 0 || bind > 0).

**Comment by axeldavy** [comment] 2018-03-04 09:57
I guess this issue is fixed now, since the patch was pushed.

**Closed by axeldavy** 2018-03-04 09:57 UTC
Labels: bug
