### ISSUE TITLE
The Elder Scrolls IV: Oblivion (Steam Version) HUD and Menu Corruption

### ISSUE THREAD

**Issue by CalcProgrammer1** [iXit/Mesa-3D#92] opened 2015-03-08 21:36 UTC
I know this bug has been reported elsewhere, but I don't see any issue for it here.  TES:IV's 2D elements are messed up with Gallium Nine enabled.  The main menu has a large white block over the bottom right of the screen and some more white blocks around the menu options.  The in-game HUD has the word "Hotkey" displayed in the middle-upper-right of the screen.  The "sneak eye" indicator always shows regardless of whether or not you are sneaking.  The health indicator bar always shows above the eye as well, even when you're out of combat.  The bottom-left HUD has a large solid rectangle behind it.  The eye and "Hotkey" text persist even when you open the Tab menu.  These do not affect the game's playability, as the game plays just fine and all the 3D rendered parts look as they should with great performance.  The alchemy menu and escape (pause) menu are fine.  I have taken a few screenshots showing these issues:

![main menu](https://cloud.githubusercontent.com/assets/1051772/6547808/3688f80e-c5b1-11e4-8d44-d62b2a57f253.png)

![game hud](https://cloud.githubusercontent.com/assets/1051772/6547809/3d65dd68-c5b1-11e4-9b14-624e72ddece9.png)

![game menu](https://cloud.githubusercontent.com/assets/1051772/6547810/4424e9c8-c5b1-11e4-98f5-50ab3c73b49b.png)

**Comment by CalcProgrammer1** [comment] 2015-03-08 21:39
My system specs:

AMD A8-3870K APU + AMD Radeon HD 5870 GPU
Ubuntu 14.10 utopic + Oibaf's PPA + Sarnex's DRI3 and Wine PPAs
MATE Desktop Environment with compositor disabled
1920x1080p TV connected via VGA to motherboard port, using DRI PRIME to offload rendering to the 5870

**Comment by axeldavy** [comment] 2015-03-21 21:53
Potentially fixed with last ixit wine and ixit Mesa. I guess you'll report when the modifications hit the ppas you are  using.

**Comment by axeldavy** [comment] 2015-11-11 13:23
We had some recent fixes for menus, can you check this is fixed ?

**Comment by CalcProgrammer1** [comment] 2015-12-05 21:03
This has not been fixed.  Just built from this repo and tested, same menu corruption as before.  The other game I reported a while ago, Saints Row 2, works fine for me now though.

**Comment by sarnex** [comment] 2015-12-06 04:17
Can you compile wine from the no-external-dll branch and take an apitrace?

**Comment by akdor1154** [comment] 2016-01-04 02:41
I'm also seeing this problem on an HD7850; tried to get wine to compile for an apitrace but running into issues with installing i386 build requirements (I'm on amd64 Ubuntu 15.10). Is it worth pursuing getting this to build on my local machine or should I just spin up a VM? (but then I'll have packaging etc to mess with getting it back to my physical machine)

**Comment by axeldavy** [comment] 2016-01-04 13:59
you don't need to compile apitrace, just take the already compiled one.

**Comment by akdor1154** [comment] 2016-01-04 23:50
sorry, I meant compiling Wine itself, it seems to need i386 versions of the -dev packages, some of which conflict with the actual amd64 mesa libs installed on my PC (I don't quite understand why these are arch-dependant, but anyway...)

**Comment by akdor1154** [comment] 2016-01-08 14:10
OK! Apitraces are up at https://drive.google.com/folderview?id=0B9Q7hIYNZJkQYnZGS09TaUtrZDg&usp=sharing , or they will be in a few hours, which is what is required in Australia to upload 200MB. :(
There are two, as I was having trouble getting nine to work, and the guys on irc reckoned that without nine should give an identical trace. There is a crash at the end of the nine trace; this is unrelated to the problem at hand. In both traces, I open Oblivion, click "continue" to load my latest save (this is as on the first screenshot above), then wait for the save to load, click "ok" to a dialog caused by a mod I have installed, then look around (this is as displayed on the second screenshot above).
Hope this helps,
Jarrad

**Comment by axeldavy** [comment] 2016-06-18 14:54
While the Hotkey test has gone, I still can't understand why the menu is buggy.

The trace enables to see the draw calls that behave differently with wine, but looking at the draw calls it's quite mysterious.

**Comment by Altosk** [comment] 2016-09-25 22:32
tested on ixit master with mesa-git on nouveau main menu is fixed didnt test anything else

**Comment by axeldavy** [comment] 2016-09-26 19:51
Indeed, I checked the trace, and it seems fixed. Great !

**Closed by axeldavy** 2016-09-26 19:51 UTC
