### ISSUE TITLE
Halo rendering bugs

### ISSUE THREAD

**Issue by zemfil** [iXit/Mesa-3D#255] opened 2016-12-01 15:02 UTC
Playing the third mission in Halo there is a peculiar rendering bug. Looking in the direction of a wall at a specific angle triggers some really bad rendering bugs, with flashing geometries and vertices flying in wrong directions (Wine has no problem here). Actually this wasn't the first time something like this happened. There is one other spot in the game where the same thing occurs, but sadly I don't have any debug logs of that, but the spot can be seen in this video: [https://youtu.be/vqFvNktMPq0?t=833](https://youtu.be/vqFvNktMPq0?t=833). It occurs when looking in the direction of the bridge from the beginning of the room (Wine fails here as well).

[Here](https://openload.co/f/ww-FI84WVxc/halo.webm) is a short video I recorded, showing the bug.

While making a debug log I strangely couldn't trigger the bug. One reason could be, while recording my fps was very low (~10-13). Making an apitrace with wine fails, as no trace is generated, but I managed to get one with Windows. Replaying the trace however is still not possible.

Another issue is with the rendering of the needler weapon. The needles are supposed to be transparent, but nine shows them in a solid white color. Wine renders the weapon correctly. Picking up the needler weapon happens at the end of the log and trace.

[needler comparison](http://screenshotcomparison.com/comparison/192412)

[nine log](http://www2.zippyshare.com/v/LAM4LZ7D/file.html)
[windows trace](http://www2.zippyshare.com/v/pPK4xDK3/file.html)

**Comment by axeldavy** [comment] 2016-12-01 18:45
it was impossible for me to find the good link for the video. Please choose a better video storage.

**Comment by axeldavy** [comment] 2016-12-01 19:16
For the apitrace bug, would be nice make a report to them, if you haven't already.

I get
Assertion failed!

Program: C:\myapitrace\d3dretrace.exe
File: /home/axel/packages/apitrace/apitrace/retrace/retrace_swizzle.cpp, Line 166

Expression: contains(it, address)

**Comment by zemfil** [comment] 2016-12-01 19:24
[video download](http://www17.zippyshare.com/v/2VGBcbwO/file.html)

**Comment by zemfil** [comment] 2016-12-09 17:37
disabling vertex shader 39 gets rid of the needler shader bug. Looking through the trace is seems shader 0x409dba0 implements that function, but I'm not entirely sure as there are a lot of shaders which closely resemble shader 39.

[VertexShader_39_CRC32_D4F3CBCC.txt](https://github.com/iXit/Mesa-3D/files/642758/VertexShader_39_CRC32_D4F3CBCC.txt)

Also I found out that the flashing textures/wrong vertices are not present when playing the game in windowed mode.

**Comment by zemfil** [comment] 2016-12-12 00:38
There are regressions in csmt, where the rendering gets crazy. It seems to affect projectiles in particular. They seem to "buffer" before they disappear .
[video](https://a.pomf.cat/auqzjv.webm)

I bisected and commit 89b52d84e70314b2485f57ddc366dbcf21fac914 (st/nine: Implement Fast path for dynamic buffers and csmt) introduced the regression.

**Comment by axeldavy** [comment] 2016-12-12 06:54
Which card are you using ?

**Comment by axeldavy** [comment] 2016-12-12 07:31
I looked at what the trace does, and it does things that are very wrong according to the spec.
I understand the behaviour will change with the commit you pointed out. Will have to check in more details what exactly is the behaviour the game relies on.

Basically in the trace I see this pattern:
. allocate buffer in SYSTEMMEM Pool with DYNAMIC flag.
. lock a small part, write to it, unlock
. lock a new small part, write to it, unlock
etc
use the buffer for drawing.
It would be all fine if the app wasn't setting DISCARD for all the locks (which allows to throw away all previous content written into the buffer).
Heaven has also a pattern where it uses DISCARD all the time, but at least it uses the buffer content written before using DISCARD again, not after.
Without the patch, radeon driver does detect the locked part wasn't locked before, and thus ignores the DISCARD.
We have to check if that is some expected behaviour for both SYSTEMMEM or DEFAULT, or just SYSTEMMEM, or if it is that SYSTEMMEM ignores DISCARD.

**Comment by zemfil** [comment] 2016-12-12 13:37
I'm using a Beema APU with iGPU and sometimes the game would crash while the bug is present. Maybe it's related, not sure.

**Comment by axeldavy** [comment] 2016-12-12 23:13
My understanding reading what the app does with apitrace is that it is really old rendering path, which tried to be friendly with very old cards. However this is bad rendering path for all the other cards.

The new problem described with the last branch with csmt work should be fixed by adding at the beginning of NineBuffer9_ctor (buffer9.c):

if (Pool == D3DPOOL_SYSTEMMEM)
    Pool = D3DPOOL_MANAGED;

I have done some tests on windows to check some of the behaviours the app expect, and SYSTEMMEM and MANAGED have the same behaviours there. Except that MANAGED should have better performance, and nine has the correct behaviour for MANAGED.

**Comment by axeldavy** [comment] 2016-12-12 23:22
Alternative is to add
if (This->base.pool == D3DPOOL_SYSTEMMEM)
        Flags &= ~D3DLOCK_DISCARD;
In NineBuffer9_Lock. I will add that to the repo.

**Comment by zemfil** [comment] 2016-12-13 03:16
The changes fixed the issue!

**Comment by axeldavy** [comment] 2016-12-14 18:57
Could you find in apitrace about a draw call with the affected shader you noticed ?

I suspect the issue is not with the shader, but with the states set. Knowing which draw call to look would help.

**Comment by zemfil** [comment] 2016-12-14 19:25
I'm not sure how I can find the drawcall responsible for shading the needles since replaying is not possible. Would an opengl trace be usefull in tracking down the bug?

**Comment by siro20** [comment] 2016-12-14 19:38
I'll have a look at the apitrace assert

**Comment by siro20** [comment] 2016-12-24 07:13
Regarding the apitrace issue:
It asserts because the game (or apitrace) writes to sysmem without locking the vertex buffer first:
```
18847 @0 IDirect3DDevice9::CreateVertexBuffer(this = 0x3d55400, Length = 196608, Usage = D3DUSAGE_WRITEONLY | D3DUSAGE_DYNAMIC, FVF = 0x0, Pool = D3DPOOL_SYSTEMMEM, ppVertexBuffer = &0x3e19220, pSharedHandle = NULL) = D3D_OK
...
1775628 @0 IDirect3DVertexBuffer9::Lock(this = 0x3e19220, OffsetToLock = 26016, SizeToLock = 1440, ppbData = &0xd51c180, Flags = D3DLOCK_DISCARD) = D3D_OK
obj 0x3e19220 <- 0x75e74208
region 0xd51c180-0xd51c720 -> 0x772335a0-0x77233b40
1775629 @0 memcpy(dest = 0xd51c180, src = blob(1440), n = 1440)
region 0xd51c180 <- 0x772335a0
1775630 @0 IDirect3DVertexBuffer9::Unlock(this = 0x3e19220) = D3D_OK
obj 0x3e19220 <- 0x75e74208
1775631 @0 memcpy(dest = 0xd51c180, src = blob(1440), n = 1440)
Assertion failed!

```

**Comment by siro20** [comment] 2016-12-24 09:15
Looks like it's apitrace fault, as it doesn't support recursive locking on buffers.

**Comment by axeldavy** [comment] 2018-03-04 10:01
Looks like this bug is fixed (patch pushed ling ago). Please reopen if not.

**Closed by axeldavy** 2018-03-04 10:01 UTC
