### ISSUE TITLE
Evoland 2 crashes on startup

### ISSUE THREAD

**Issue by kode54** [iXit/Mesa-3D#332] opened 2019-01-01 04:39 UTC
Running Evoland 2 once again, on Arch, using wine-staging-nine 4.0-rc4 from the official repository, and now it crashes if I have Gallium Nine enabled. I'll attach a log, with probably useless symbols from debug lib32-mesa 18.3.1.

[evoland2.log](https://github.com/iXit/Mesa-3D/files/2719117/evoland2.log)

It works perfectly with WineD3D on the same hardware.

Once again, I'm linking to the same traces file, as the included evoland2_d3d9_working.trace made from Windows manages to make Gallium Nine 18.3.1 crash on amdgpu/radeonsi, in the r600 code somewhere?

[evoland2_traces.tar.xz](https://f.losno.co/evoland2_traces.tar.xz) (199.3MB)

**Comment by iiv3** [comment] 2019-01-02 10:11
It's regression, mesa-18.2.0 works, while mesa-18.3.0 crashes.

The backtrace from the log is misleading, it shows R600 ShaderBackend functions, but they are just the closest symbols it could find. With debug it actually looks like this:
```
  1 0xf7327dd1 work_present+0x620(data=<is not available>) [/tmp/mesa-18.4.100/src/gallium/state_trackers/nine/swapchain9.c:106] in d3dadapter9.so.1 (0x00000000)
  2 0xf7327ebd create_present_buffer+0x7c(This=0x7cc9d200, width=<is not available>, height=<is not available>) [/tmp/mesa-18.4.100/src/gallium/state_trackers/nine/swapchain9.c:604] in d3dadapter9.so.1 (0x00000000)
  3 0xf73287b5 NineSwapChain9_Present+0x264(This=<couldn't compute location>, pSourceRect=<couldn't compute location>, pDestRect=<couldn't compute location>, hDestWindowOverride=<couldn't compute location>, pDirtyRegion=<couldn't compute location>, dwFlags=<couldn't compute location>) [/tmp/mesa-18.4.100/src/gallium/state_trackers/nine/swapchain9.c:812] in d3dadapter9.so.1 (0x0032fc48)
  4 0xf72ec787 LockSwapChain9_Present+0x66() [/tmp/mesa-18.4.100/src/gallium/state_trackers/nine/nine_lock.c:2770] in d3dadapter9.so.1 (0x0032fcb8)
  5 0xf7acd2db WineNineSwapChain9_Present+0x3a() in d3d9-nine<elf> (0x0032fd18)
  6 0x00448a47 EntryPoint+0x4363f() in d3dretrace (0x0032fd64)
```

It looks like #331. However reverting `1cc8192ad0be52220043d40f2c7ead149d479809` , does not seem to fix the issue ("Tomb Raider" trace does work, but "Evoland2" does not).

I'll try to bisect this issue.

**Comment by iiv3** [comment] 2019-01-02 18:31
The bisect landed me on :
```
commit 2318ca68bbeb4fa6e21a4d8c650cec3f64246596
"st/nine: Handle window resize when a presentation buffer is used"
```

I prod the code a little.
In `swapchain9.c::present()` , both bugs happen when `target_width` and `target_height` are `0`.
This causes `create_present_buffer()` to fail obtaining `*resource` from `This->screen->resource_create()`, the crash happens when that `resource` is passed to the device driver.

Adding zero checks seems to fix it. Not sure if it is the optimal solution.

**Comment by axeldavy** [comment] 2019-01-02 21:16
I added the zero check for the window size, does it fix the issue ?

**Comment by iiv3** [comment] 2019-01-02 21:32
It fixes the "Evoland 2" and "Tomb Rider" trace playback for me.

I may still prefer a more robust check, e.g. `target_height < 8`. Assuming the minimum buffer size is of one 8x8 block.

**Comment by kode54** [comment] 2019-01-03 04:39
It’s probably pointless to suggest, but maybe Wine has already documented special parameter values or other limits checking in their WineD3D implementation?

**Comment by axeldavy** [comment] 2019-01-03 18:37
I failed to see any special handling for that. But they likely don't need anything because they have access to the true internal size of the target drawable, which we don't (we use other wine functions that should give the same value, and maybe there is special init case where it would return 0, 0 for these, but do something else for the wine internal functions).

**Comment by iiv3** [comment] 2019-01-03 20:34
@kode54, can you confirm that the commit fixes the issue for the real game?

@axeldavy, I would prefer to have this fix in upstream asap.

**Comment by kode54** [comment] 2019-01-04 02:51
First I have to build llvm/llvm-libs/clang from svn, then build Mesa from Git. The llvm-svn collective is progressing nicely, it's already at 78% finished after about an hour or two.

I know Mesa itself only takes about 15-20 minutes to compile, so this should be relatively quick....

Oh wait, crap. I built the 64 bit version of this stuff. I need the multilib versions of this stuff too.

**Comment by iiv3** [comment] 2019-01-04 14:11
You don't need to compile your own LLVM from git. The distribution binary package should be good enough. All you need is the development headers, no idea if Archlinux keeps them separate (like Debian).

Are you sure you have applied the patch to your build? From the log it looks like you are compiling the upstream mesa git. The patch is not merged upstream yet.

Here is an easy link to the patch you can apply to the source (with `patch`).
https://github.com/iXit/Mesa-3D/commit/a964acd8fdf365c6a8636949d41b9dac5364ff5c.patch

**Comment by kode54** [comment] 2019-01-04 23:00
I used the Arch Linux mesa-git package, and I altered the source URL to point to this Github repository, which I already found the patch included in master. I verified that the patch was in the source tree that it compiled.

**Comment by iiv3** [comment] 2019-01-05 11:43
Would you add the following code:

```
--- a/src/gallium/state_trackers/nine/swapchain9.c
+++ b/src/gallium/state_trackers/nine/swapchain9.c
@@ -809,6 +815,8 @@ present( struct NineSwapChain9 *This,
             struct pipe_resource *new_resource;
             D3DWindowBuffer *new_handle;
 
+printf("\n nine: target_width=%d target_height=%d, resource->width0=%d, resource->height0=%d \n ",
+              target_width,   target_height,    resource->width0,    resource->height0);
             create_present_buffer(This, target_width, target_height, &new_resource, &new_handle);
             /* Switch to the new buffer */
             if (new_handle) {
```
The new code is with `+`, in case the patch does not apply and you have to add it with text editor.

This code should still crash.But right before the crash it would print the values of these 4 variables.
Give us just the output of that line, the rest of the backtrace should be the same as the old one.

I suspect that `resource->width0/height0` might also be zero, thus triggering the bug again, and that block is not bypassed, because it checks `target_width/height` against `This->present_buffers[0]->width/height` .

@axeldavy , maybe you should add error handling case for `*resource == NULL` in `create_present_buffer()` , at least the rest of the code checks the value returned in `**present_handle`.
And don't forget to add some debug output to it, in case this causes more troubles elsewhere.

**Comment by axeldavy** [comment] 2019-01-05 11:46
by any chance, when you meant 'compile mesa from git' maybe you meant official mesa, and not this github repo ?

**Comment by iiv3** [comment] 2019-01-05 12:19
@axeldavy, he did say "this Github repository".
Also his previous post had link to a backtrace log and the line numbers matched the ones with the patch applied.

**Comment by axeldavy** [comment] 2019-01-05 14:43
I get nine: target_width=5898332 target_height=1850160, resource->width0=967, resource->height0=546 

weird...

**Closed** 2019-01-05 18:12 UTC

**Comment by kode54** [comment] 2019-01-06 02:56
I'm verifying this workaround after I rebuild mesa-git and lib32-mesa-git from this repository, and would love to test the wine side fix as well, whenever that materializes.

**Comment by axeldavy** [comment] 2019-01-08 17:55
we merged the wine fix on the iXit/wine repo

**Comment by iiv3** [comment] 2019-01-09 10:41
Is it this one: https://github.com/iXit/wine/commit/c5919d380ad2e1f6fa5bd440f60c946a023e7b88 ?
