### ISSUE TITLE
Witcher-1 regression

### ISSUE THREAD

**Issue by rox4d** [iXit/Mesa-3D#347] opened 2019-04-11 18:03 UTC
commit a3ddb47ab22d2e2830e154d1bb3f8973a8c5edab Introduce regression in Witcher-1.

**Comment by axeldavy** [comment] 2019-04-11 18:06
Thank you for your testing, this patch is not merged to main mesa because I thought indeed more tests were needed.
It is though the first regression reported with the current state of the patch. Would you provide a trace showing the issue, or show debug info with and without the patch (NINE_TGSI_DUMP=1 NINE_DEBUG=shader R600_DEBUG=vs,ps   needs mesa with -D b_ndebug=false)

**Comment by rox4d** [comment] 2019-04-11 18:47
Uploaded (again).
https://drive.google.com/open?id=1egl3Yd9IUyFPQ9Q9f2dzkYHBjPUqxR7l

**Comment by axeldavy** [comment] 2019-04-11 18:57
sorry, hadn't realized we had a trace already

**Comment by axeldavy** [comment] 2019-04-11 19:24
Do you have the same issue as in https://github.com/iXit/Mesa-3D/issues/312 ? What is the regression ?

**Comment by rox4d** [comment] 2019-04-11 20:07
No, by saying about regression I was meaning only that game was working before and then broken.
![Снимок экрана в 2019-04-11 23-03-42](https://user-images.githubusercontent.com/34712490/55989085-2b2dd680-5cae-11e9-9b23-b477c495eacb.png)

**Comment by axeldavy** [comment] 2019-04-12 22:18
I found the bug (fog constants not copying enough values from the main constant buffer) and fixed the bad commit.

**Closed by axeldavy** 2019-04-12 22:18 UTC
