### ISSUE TITLE
Dishonored causes a lockup on SI.

### ISSUE THREAD

**Issue by sarnex** [iXit/Mesa-3D#133] opened 2015-08-29 18:21 UTC
When I play dishonored with nine, I get a lockup after a few minutes in the game. The trace is in the major bugs folder. There is no lockup on r600 or wined3d. The hang still occurs on LLVM 3.5.2, 3.6.1 and git. R600_DEBUG=ps,vs and dmesg @ freedesktop link

first bad frame: 2123

first bad call: 25280540 @1 IDirect3DDevice9::DrawIndexedPrimitive(this = 0x7d500428, PrimitiveType = D3DPT_TRIANGLELIST, BaseVertexIndex = 0, MinVertexIndex = 0, NumVertices = 153, startIndex = 0, primCount = 61) = D3D_OK

Freedesktop reference https://bugs.freedesktop.org/show_bug.cgi?id=90997

**Comment by axeldavy** [comment] 2018-09-15 17:44
As the freedesktop link says the issue is fixed, I close this instance.

**Closed by axeldavy** 2018-09-15 17:44 UTC
